language: node_js
node_js:
  - node
before_deploy: yarn
deploy:
  provider: npm
  email: ulisesantana@gmail.com
  api_key:
    secure: Z27XomH605T8YAArQ5hHm5zcdDVucN3xNKHi++Ny57capzCt3JIx8iBDIn9jrL032C7X97dhqAW0we6NVnVCwN+MBkwdeHGrt0L3S6eMsk41T5DUufa0jNSWK4/EuPXLbR/lVZbeCuSMQ9XjVbyn4Kui62WwigjUPuCFEVmv45pAix3crmTsDRtGY6bM82geVE9UAAqMdYfF/3c4xZV0LGMEV91lqhxCNFSbgNMMcKGSyHzN+d/ZtEYDyKIpQl6VHZ6mrEWrqOT8g8G+RwY62VR868DOo9uk0OJ+NBJPbIm4KlmjQh3DA9XCgot92uQaD4ZV3ETxXJDG5jjlJqMk+iWA+BsVO/a37AJ4S24kW1PFGk+K3Y/k1JD2w6Y1EAGinjm9bU2VYAZ70lxAEQi5cHzj7mnfqFbdiQXdNdwLAPmDaninooEAPmx7RaxHAr6IGvaDlMNRbyvqhnD29zgrDAawC8T3LXib5PgE6APa12d2bd+nhCceU6n0Kplj/aKaviVzgCgk1938GbAX4XoyaHerTxVj/nJF7nrCmyNGYZl7pZbEmSFBWaK765TXWOZV3UbfnHHNXvb/ShhEVxnI0YQ2LYxhlLDA34xv1UIR0cQXerPh7C659tycymXv786A7k7+p+hdMbzkhG+p0IjsFXSIuT3851clfJwMC0r30+g=
  on:
    repo: ulisesantana/todo-cli
